lib/instana/tracer.rb, test/tracing/tracer_test.rb
=> Improved ID <--> Header conversions & Tests

lib/instana/frameworks/rails.rb, lib/instana/instrumentation.rb
This fixes/implements/resolves #21
=> When in Rails, auto insert ::Instana::Rack into middleware

Configuration.md, Gemfile, lib/instana/agent.rb, lib/instana/base.rb, lib/instana/frameworks/sinatra.rb, lib/instana/instrumentation/net-http.rb, lib/instana/logger.rb, lib/instana/tracing/processor.rb, lib/instana/version.rb, test/apps/sinatra.rb, test/instrumentation/sinatra_test.rb, test/test_helper.rb
This instrumentation auto configures Sinatra and Padrino with the Instana Rack middleware.
=> Add Rack support for Sinatra & Padrino

lib/instana/agent.rb, lib/instana/tracing/span.rb, lib/instana/tracing/trace.rb, test/instrumentation/net-http_test.rb, test/tracing/custom_test.rb, test/tracing/trace_test.rb, test/tracing/tracer_test.rb
Custom traces are currently shown as Unknown in the UI.  If we swap to using the SDK/API, these will have greater support/display in Instana.
=> For custom traces, the gem should report using the SDK API for spans

Gemfile, lib/instana/instrumentation/rest-client.rb, lib/instana/tracing/trace.rb, lib/instana/version.rb, test/instrumentation/rest-client_test.rb
This adds instrumentation for the rest-client gem and tests
to validate.
=> RestClient Instrumentation

lib/instana/agent.rb, lib/instana/base.rb, lib/instana/collectors.rb, lib/instana/collectors/gc.rb, lib/instana/instrumentation/net-http.rb, lib/instana/logger.rb, lib/instana/util.rb
Some cleanup, centralization and general improvements.
=> Refactor and cleanup

lib/instana/agent.rb
We should add protection around the timer runs to make sure that there are no backlogs of timer activations.  If so, then skip the current run.
=> Under high load, timer runs can get backed up

lib/instana/util.rb
This fix improves process name recognition by the host sensor.
=> Fixed process detection under Kubernetes

lib/instana/agent.rb, lib/instana/util.rb
Remove environment variables from process name under OSX
=> Improved OSX process reporting.

Gemfile, lib/instana/agent.rb, lib/instana/collectors/gc.rb, lib/instana/frameworks/cuba.rb, lib/instana/frameworks/instrumentation/action_controller.rb, lib/instana/frameworks/instrumentation/action_view.rb, lib/instana/frameworks/instrumentation/active_record.rb, lib/instana/frameworks/rails.rb, lib/instana/frameworks/roda.rb, lib/instana/frameworks/sinatra.rb, lib/instana/instrumentation/dalli.rb, lib/instana/instrumentation/excon.rb, lib/instana/instrumentation/net-http.rb, lib/instana/instrumentation/rack.rb, lib/instana/instrumentation/rest-client.rb, lib/instana/util.rb, test/test_helper.rb
More cleanup to lower the verbosity of the gem.
=> Fix deprecation warning; improve logging; Reuse http client

lib/instana/eum/eum-test.js.erb
This updates the URL which EUM spans are reported to.
=> Update EUM test reporting URL

lib/instana/instrumentation/sidekiq-client.rb, lib/instana/instrumentation/sidekiq-worker.rb, test/instrumentation/sidekiq-client_test.rb, test/servers/helpers/sidekiq_worker_initializer.rb
This PR updates the sidekiq instrumentation to also report the Redis server
that Sidekiq is connected to so that Instana can resolve the physical entity
on the dashboard.
=> Sidekiq: Report Redis URL

lib/instana/config.rb, lib/instana/instrumentation/redis.rb, lib/instana/tracing/span.rb, test/instrumentation/redis_test.rb, test/instrumentation/sidekiq-client_test.rb, test/instrumentation/sidekiq-worker_test.rb, test/test_helper.rb
Hi @pglombardo, this is the pull implementing the Redis instrumentation. Although I almost finished it, I'm really confused whether we should add this instrumentation into standard sensor or just let the users handle it by themselves. At my company, we have complicated Redis usage, so the instrumentation is essential. However, I'm not sure about other people's usage. So, in case you consider this instrumentation does not belong to standard sensor, please let me know and just close this pull. I'll move this into a plugin for my company 😃
=> Redis instrumentation

Gemfile, benchmarks/Gemfile, benchmarks/Gemfile.lock, benchmarks/id_generation.rb, gemfiles/libraries.gemfile, gemfiles/rails32.gemfile, gemfiles/rails42.gemfile, gemfiles/rails50.gemfile, lib/instana/logger.rb, lib/instana/util.rb
Using this PR to pull together some past and new benchmarks.  Hunting down latest additions for any performance regressions.
=> Performance improvement: Don't create a new Integer Range on each ID generation

lib/instana/instrumentation/rack.rb
https://bugs.ruby-lang.org/issues/13539
=> Require entire CGI due to Ruby 2.4.1 bug #13539

lib/instana/tracing/processor.rb
This avoids a potential connection reset from the host agent
when we send many spans at once (6k+) when under load.
=> Report spans in batches

lib/instana/config.rb, lib/instana/tracing/span.rb, test/instrumentation/excon_test.rb, test/instrumentation/net-http_test.rb, test/tracing/trace_test.rb
=> Disable backtrace collection by default; add config option

lib/instana/tracing/trace.rb
Assure that current_span has a value before operating on it.
=> Add Tracing safeties

lib/instana/tracing/span.rb, test/agent/agent_test.rb, test/instrumentation/net-http_test.rb, test/test_helper.rb, test/tracing/custom_test.rb, test/tracing/opentracing_test.rb, test/tracing/tracer_async_test.rb
Nest OT tags under a 'tags' hash
=> Fix Opentracing tag storage in span

.travis.yml, lib/instana/test.rb
Change default DB flavor to test against
=> Test suite cleanup & improvements

.travis.yml, gemfiles/rails42.gemfile, gemfiles/rails50.gemfile
https://github.com/brianmario/mysql2/issues/950
=> Fix tests: Limit myslq2 version to avoid a bug in 0.4.10

lib/instana/tracing/trace.rb, test/tracing/tracer_async_test.rb
Update to how we report asynchronous spans to Instana.
=> Change async span flag to deferred

lib/instana/agent.rb, lib/instana/base.rb, lib/instana/logger.rb
* Boot message (Stan is on the scene) is now INFO level
* Add log message hint re: setting env var INSTANA_QUIET=1
* Add INSTANA_DEV env var support to enable DEBUG output
=> Improve logger levels, hints and env vars

Configuration.md, lib/instana/instrumentation.rb, lib/instana/util.rb
Add support for the `INSTANA_SERVICE_NAME` and `INSTANA_DISABLE_AUTO_INSTR` environment variables.
=> Add support for common configuration

lib/instana/tracing/span.rb
Updates how stack traces are reported.
=> Update stack reporting key

instana.gemspec, lib/instana/util.rb
Adds support for versions back to 2011.
=> Expand Legacy support for ffi, oj and sys-proctable

lib/instana/tracing/span.rb, test/tracing/opentracing_test.rb
Default to intermediate if not specificed
=> OpenTracing: Update and improve span.kind handling

Rakefile, lib/instana/instrumentation/rack.rb, test/frameworks/rack_test.rb
This PR improves the custom header collection and reporting.  Included also are tests to validate proper collection.
=> Update custom header reporting and add tests

lib/instana/agent.rb, lib/instana/agent/helpers.rb
Updates to support AnnounceUtil
=> Improved Announce Process

.travis.yml, Rakefile, gemfiles/rails60.gemfile, lib/instana/frameworks/instrumentation/action_view.rb, test/frameworks/rails/actionview5_test.rb, test/models/block6.rb, test/servers/rails_3205.rb, test/test_helper.rb
Updates to fix the Rails 6 ActionView instrumentation issues reported in #177.
Closes #177
=> Fix: Rails 6 ActionView Instrumentation & Tests

lib/instana/config.rb, lib/instana/frameworks/instrumentation/mysql2_adapter.rb, lib/instana/frameworks/instrumentation/mysql_adapter.rb, lib/instana/frameworks/instrumentation/postgresql_adapter.rb, lib/instana/tracing/span.rb, test/frameworks/rack_test.rb, test/frameworks/rails/activerecord_test.rb, test/instrumentation/excon_test.rb, test/instrumentation/redis_test.rb
Testing all three on top of the GraphQL work before merging.
=> Clean up open pull requests

.circleci/config.yml, .gitignore, Rakefile, test/test_helper.rb
Coverage reporting is broken until
https://jira.sonarsource.com/browse/SONARSLANG-477
gets resolved
=> Configure Sonarqube

lib/instana/backend/host_agent.rb, lib/instana/backend/serverless_agent.rb, lib/instana/frameworks/roda.rb, lib/instana/instrumentation/aws_sdk_s3.rb, lib/instana/instrumentation/aws_sdk_sns.rb, lib/instana/instrumentation/aws_sdk_sqs.rb, lib/instana/instrumentation/instrumented_request.rb, lib/instana/instrumentation/rack.rb, lib/instana/instrumentation/shoryuken.rb, lib/instana/snapshot/docker_container.rb, lib/instana/snapshot/fargate_task.rb, lib/instana/snapshot/google_cloud_run_instance.rb, lib/instana/tracing/span_context.rb
Tested with ruby. 2.2.2 version
=> Retrocompatibility with <2.4 ruby versions

.circleci/config.yml, lib/instana/activator.rb, test/test_helper.rb, test/tracing/instrumented_logger_test.rb
* Report tests as Junit
* Run Sonarqube Once
=> CircleCI Cleanups

lib/instana/tracing/span.rb
- Dry up the method implementation.
- We now take the top 30 entries as the report on errors.
=> Clean up #add_stack

.circleci/config.yml, lib/instana.rb, lib/instana/backend/host_agent_activation_observer.rb, lib/instana/base.rb, test/backend/host_agent_activation_observer_test.rb
=> Fix reported issues

lib/instana/activators/sinatra.rb
This resolves some underlying issue with Passenger 6.
=> Ensure that ::Sinatra::Base.middleware is defiend.

.github/ISSUE_TEMPLATE/config.yml
Signed-off-by: Ferenc Géczi <ferenc.geczi@ibm.com>
=> docs: add link to AHA for feature requests to github issue template

.github/workflows/pr_commits_signed_off.yml, CONTRIBUTING.md, MAINTAINERS.md
Signed-off-by: Ferenc Géczi <ferenc.geczi@ibm.com>
=> [chore] Mention DCO in CONTRIBUTING.md and enforce it with workflow

.circleci/config.yml
Fixes CircleCI's warning about deprecated images.
More information on the image deprecation is available here:
https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
=> ci: Fix warning about deprecated images

.circleci/config.yml, instana.gemspec
Fixes: https://github.com/instana/ruby-sensor/issues/283
=> [fix] Set the required ruby version to the supported minimum

test/instrumentation/rails_action_controller_test.rb, test/support/apps/action_controller/config.ru, test/support/apps/rails_generic/config.ru
Covers legacy code plus the recently added https://github.com/instana/ruby-sensor/pull/355
=> test: Cover Rails.logger

.tekton/.currency/resources/table.json
Update support policy in ruby currency report.
Signed-off-by: Varsha GS <varsha.gs@ibm.com>
=> report(currency): update support policy

lib/instana/backend/host_agent.rb, test/backend/host_agent_test.rb
notify observers before deleting
=> notify observers before deleting

lib/instana/version.rb
=> release: version 1.215.1

lib/instana/version.rb
Release which includes support for sequel gem
=> release: 1.216.0

.tekton/.currency/docs/report.md, .tekton/.currency/resources/table.json, .tekton/.currency/scripts/generate_report.py, .tekton/pipeline.yaml, .tekton/task.yaml, gemfiles/sequel_56.gemfile, gemfiles/sequel_57.gemfile
Adding sequel gem to currency reports.
=> sequel: add gem to currency reports

.tekton/pipeline.yaml
tekton: remove the test for excon-021 and match circle-ci pipeline
=> tekton: remove the test for excon-021 and match circle-ci pipeline

.circleci/config.yml, Rakefile
CI: start ruby 3.4 preview2 testing
=> CI: start ruby 3.4 preview2 testing

gemfiles/rails_71.gemfile
Temporarily stop testing for rails 8.
=> stop testing for rails 8

lib/instana/version.rb
=> release: 1.217.0

lib/instana/version.rb
=> release: 1.217.1

.circleci/config.yml
=> chore: start ruby 3.4.1 testing

Gemfile, instana.gemspec, lib/instana/base.rb, lib/instana/samplers.rb, lib/instana/setup.rb, lib/instana/trace.rb, lib/instana/trace/export.rb, lib/instana/trace/processor.rb, lib/instana/trace/span.rb, lib/instana/trace/span_context.rb, lib/instana/trace/span_kind.rb, lib/instana/trace/span_limits.rb, lib/instana/trace/tracer.rb, lib/instana/trace/tracer_provider.rb, lib/instana/util.rb, test/tracing/processor_test.rb, test/tracing/span_test.rb, test/tracing/tracer_async_test.rb, test/tracing/tracer_provider_test.rb, test/tracing/tracer_test.rb
=> Move tracer to OTEL standards

.circleci/config.yml
Update the docker registries and change the matrix generation structure
=> Update the docker registries and change the matrix generation

lib/instana/instrumentation/mongo.rb, lib/instana/instrumentation/net-http.rb, lib/instana/instrumentation/rack.rb, lib/instana/instrumentation/rest-client.rb, test/instrumentation/mongo_test.rb, test/instrumentation/net_http_test.rb, test/instrumentation/rails_active_record_database_missing_test.rb, test/instrumentation/rails_active_record_test.rb, test/instrumentation/rest_client_test.rb
Otel instrumentation part 2 with some fix in failures.
=> Otel instrumentation

examples/otel.rb, lib/instana/trace/tracer.rb
=> otel: add examples and method desc

README.md, lib/instana/version.rb
adding OTel specified  methods to the tracer
remove support for opentracing
=> release: V2.0.0

.github/workflows/release-notification-on-slack.yml
=> chore: fix broken notifications
