Gemfile
lib/instana.rb
lib/instana/agent.rb
lib/instana/collectors.rb
test/agent_test.rb
test/test_helper.rb

The Ruby code should 
1. detect when the host agent is offline and stop attempting to report metrics at least for a short period of time before a retry.
2. Periodically re-announce sensor when needed
3. Have a timeout for HTTP operations

Agent error handling should be improved

---

instana.gemspec

I just dropped this gem into a rails app.  The following `bundle install` command failed with the error message:
```
Installing hitimes 1.2.4 with native extensions
Installing get_process_mem 0.2.1
Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES section: 'ffi'
```
Adding `ffi` to my Gemfile caused the bundle install to succeed.

Undocumented implicit dependency `ffi`

---

lib/instana/agent.rb
test/agent_test.rb

In the case of Docker running in bridged network mode, the gem still tries to communicate with 127.0.01 but instead it should use the default gateway.
https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach

Gem doesn't bind to host agent under Docker in bridged mode

---

lib/instana/agent.rb
test/agent_test.rb

* Properly detect process ID under docker (and not)
* Better discovery announcements and handling
* Handle announcement responses
* Add pid namespace detection method
* Add method to detect true pid on linux

Improved Docker support.

---

.travis.yml
lib/instana.rb
lib/instana/agent.rb
lib/instana/collectors/gc.rb
lib/instana/collectors/memory.rb
lib/instana/collectors/thread.rb

Set the initial log level based on environment.  Update
code to use proper log levels in rescue blocks.

Use proper logging log levels

---

lib/instana/tracing/trace.rb
test/tracing/trace_test.rb

```
Numeric value (13086791889175417122) out of range of long (-9223372036854775808 - 9223372036854775807)
```
Need to limit the size that the ID generator generates.

Ruby generating Trace IDs that are too large

---

lib/instana/agent.rb
lib/instana/instrumentation/rack.rb
test/tracing/trace_test.rb

This PR add support, detection and handling for forks (such as for forking webservers as unicorn/puma etc).  We fall back to unannounced state, re-initialize and then continue business as usual.

Ruby Sensor not detecting/handling forking webservers correctly

---

lib/instana.rb
lib/instana/agent.rb
lib/instana/base.rb
lib/instana/setup.rb

Per feedback from @ntl.  The Ruby sensor should have a way to optionally control when/how the background thread is started/executed.  The current default is acceptable but having a secondary option per require option in the Gemfile would be ideal:
`gem "instana", :require "instana/setup"`
This would do basic initialization but not boot/execute the background thread.  With this option, the user can control where/how the background thread is run/manages.

Agent background thread init/start should be configurable

---

lib/instana/tracer.rb
lib/instana/tracing/trace.rb
test/tracing/tracer_test.rb

The Ruby agent generates IDs for traces.  We're currently only generating a subset of the total IDs possible.

Traces aren't using the full range of IDs possible

---

lib/instana/agent.rb
lib/instana/base.rb

In the case of forking webservers such as Unicorn or Puma in clustered mode, when fork is called, only the calling thread is copied to the new process.  Hence no background agent thread.
We currently don't detect this but should.

Agent should independently detect forks and act appropriately

---

lib/instana/agent.rb
lib/instana/tracing/processor.rb

For quick ruby scripts, traces in queue are destroyed along with the process & threads.  We should add an ensure block to the thread loop to make sure traces/metrics are flushed to the host agent before exiting.

Traces are not flushed for short-lived ruby scripts

---

Configuration.md
Gemfile
lib/instana/agent.rb
lib/instana/base.rb
lib/instana/logger.rb

This logger allows the debug level to be configured that affects
what it reports.  For this first iteration, it allows for:
* `:agent` - shows all agent state related debug messages
* `:agent_comm` - outputs all request/response pairs to and from the host agent
Log messages can be generated for these channels using:
```Ruby
::Instana.logger.agent("agent specific log msg")
::Instana.logger.agent_comm("agent communication specific log msg")
```
To set the debug log level:
```Ruby
::Instana.logger.debug_level = [:agent, :agent_comm]
::Instana.logger.debug_level = [:agent_comm]
::Instana.logger.debug_level = :agent
```
or to reset it:
```Ruby
::Instana.logger.debug_level = nil
```

Custom Instana logger for better logging control

---

lib/instana/collectors.rb
lib/instana/tracing/processor.rb
lib/instana/tracing/trace.rb
test/instrumentation/rest-client_test.rb
test/tracing/tracer_async_test.rb

Instead of a registered span, report rest-client as an
sdk span.

Change RestClient instrumentation to report using SDK

---

lib/instana/agent.rb
lib/instana/instrumentation/excon.rb
lib/instana/instrumentation/net-http.rb

This normalizes the "instrumenting" messages and now outputs user friendly messages with the default log level in place.
This screenshot shows a successful boot of the stack and having the host agent go offline for a period.

Better state messages with default logging.

---

.codeclimate.yml
lib/instana/instrumentation/excon.rb
lib/instana/instrumentation/net-http.rb
lib/instana/instrumentation/rack.rb
lib/instana/logger.rb
lib/instana/tracing/trace.rb
lib/instana/util.rb
test/instrumentation/net-http_test.rb

This improves error logging, backtrace handling
and now marks HTTP client spans with 5xx response
codes as errored.

Improved Error Handling & Reporting

---

lib/instana/util.rb

This reports the list of gems in use by the Ruby app to the dashboard and displays them in the sidebar.  See screenshot below.

Add Gem bundle to snapshot

---

lib/instana/agent.rb
test/agent/agent_test.rb

This PR separates discovery out into it's own method (`run_discovery`), utilizes any customer configured host/port pair (via `::Instana.config[:agent_host]` and `::Instana.config[:agent_port]`) and has more debug output for diagnosing any potential errors.

Better host agent discovery & tests

---

Configuration.md
lib/instana/collector.rb
lib/instana/config.rb
lib/instana/logger.rb
lib/instana/tracer.rb
test/config_test.rb
test/tracing/tracer_test.rb

This PR adds the ability to enable/disable:
1. the entire gem globally (for prebuilt environments)
2. tracing
3. metrics
```
Instana.config[:enabled] # default true
Instana.config[:metrics][:enabled] # default true
Instana.config[:tracing][:enabled] # default true
```

Add global enable/disable config options

---

lib/instana/instrumentation/net-http.rb
test/instrumentation/net-http_test.rb
test/servers/rackapp_6511.rb

This fixes the error handling of 5xx responses with Net::HTP and
adds tests to validate.

Fix error logging of Net::HTTP 5xx responses

---

lib/instana/agent.rb

Found on one of my ubuntu servers:
```
Instana: announce_sensor:agent.rb:193: No such file or directory @ rb_sysopen - /proc/26331/sched
```

Check existence of sched file before attempting to open.

---

lib/instana/frameworks/instrumentation/action_controller.rb
test/frameworks/rails/actionview3_test.rb
test/frameworks/rails/actionview4_test.rb
test/frameworks/rails/actionview5_test.rb
test/servers/rails_3205.rb

When rendering a _default_ view, there may not be a partial or layout name available to the sensor (or is there?).  In any case, showing "unknown" could be impoved upon.
Still to do - add support for:

ActionView Span can show Unknown

---

lib/instana/agent.rb

In OSX development environments, either spring or puma is rewriting the process command line name which causes the agent to fail to announce.
Other processes announce fine (Linux, OSX Ruby console, OSX other stacks).
The screenshot below shows the rewritten command line (in the bottom window) and what the Ruby process thinks (top window).

OSX development environment with Spring/Puma causes failed announce

---

lib/instana/tracer.rb
lib/instana/util.rb
test/tracing/id_management_test.rb

It's likely that the Ruby conversion requires a 16 char string.  When leading zeros are dropped by any other language this ruby sensor won't convert into the correct value.
We should prepend any header values with zeros if length < 16 prior to converting.

Header values with leading zeros can be incorrectly converted

---

lib/instana/frameworks/instrumentation/active_record.rb

Just by accessing `connection` it resolves eventually to `new_connection` which is undesired in case we are running outside of the intended environment (such as building a docker image or running rake tasks).
We should avoid accessing `ActiveRecord::Base.connection.adapter_name` here:
https://github.com/instana/ruby-sensor/blob/master/lib/instana/frameworks/instrumentation/active_record.rb#L8

ActiveRecord: Accessing adapter name triggers DB connection

---

lib/instana/tracing/span.rb
lib/instana/tracing/trace.rb

Similar to what OT [set_tag](https://github.com/instana/ruby-sensor/blob/master/lib/instana/tracing/span.rb#L275) does, [add_info](https://github.com/instana/ruby-sensor/blob/master/lib/instana/tracing/trace.rb#L82) should also support the proper translation when `span.kind` is set.

log_info/add_info should properly translate span.kind

---

lib/instana/agent.rb
lib/instana/collectors/gc.rb
lib/instana/collectors/memory.rb
lib/instana/collectors/thread.rb
lib/instana/helpers.rb
lib/instana/util.rb

This PR improves logging by lowering the logger levels of non-critical exceptions from `error` down
to `info` or `debug`.

Lower logging verbosity & levels

---

.gitignore
gemfiles/libraries.gemfile
lib/instana/config.rb
lib/instana/instrumentation/grpc.rb
test/apps/grpc_server.rb
test/instrumentation/grpc_test.rb
test/servers/grpc_50051.rb
test/test_helper.rb

Hello there, my name is Minh Nguyen, from Employment Hero. I have a talk with Peter in Instana support center about the gRPC support. This pull is the implementation of gRPC support for the Ruby Sensor. As gRPC is official supported by Google and a official library is provided (https://github.com/grpc/grpc/tree/master/src/ruby), I follow the implementation of this library. I already test in my Company's environment and everything works like charm, except some problems with front-end display because `rpc-client` and `rpc-server` span kinds are not supported yet. So in this implementation, I treat `rpc-client` and `rpc-server` as a custom span kind. Perhaps after you guys add the support for them, I'll add to the registered span list.
Please give me some feedbacks about this implementation. …

GRPC instrumentation implementation

---

gemfiles/libraries.gemfile
lib/instana/tracing/span.rb
test/instrumentation/grpc_test.rb

This should be reported as a registered span as `rpc-client` and `rpc-server` are registered span types.
Also some UI issues to be resolved:
cc: @nguyenquangminh0711 FYI some polishing work for me to do on our backend & UI.

Grpc Instrumentation is reported using SDK span type

---

instana.gemspec
lib/instana/tracing/processor.rb
test/instrumentation/grpc_test.rb

This lowers the version requirement of ffi to 1.8.1 (from April 2013).
By default, a first time `bundle install` or a `bundle update` will always get the latest version available but this helps those who may have previously version locked ffi to an earlier version (either directly or indirectly via another gem).

Lower runtime version requirement for ffi

---

lib/instana.rb
lib/instana/agent.rb
lib/instana/tracing/processor.rb

We've found a case where the background thread may be non-existent (e.g it dies or is killed).
In such a case, Ruby metrics are no longer reported, and the trace queue fills up indefinitely.
This PR tracks the spawned thread and makes occasional checks on it's health.
It will respawn the background thread if needed.

Track and occasionally check background thread

---

instana.gemspec

Some users are locked into an earlier version of timers that we currently allow.  This PR lowers the minimum version required (v4+).

Loosen up the dependency on timers to >= 4.0

---

.travis.yml
Rakefile
benchmarks/opentracing.rb
benchmarks/time_processing.rb
gemfiles/rails32.gemfile
gemfiles/rails42.gemfile
instana.gemspec
lib/instana/agent.rb
lib/instana/tracer.rb
lib/instana/tracing/span.rb
lib/instana/tracing/trace.rb
lib/instana/util.rb
test/benchmarks/bench_id_generation.rb
test/benchmarks/bench_opentracing.rb
test/test_helper.rb
test/tracing/custom_test.rb
test/tracing/opentracing_test.rb
test/tracing/tracer_test.rb

We currently use a Time object, convert it to a float, multiply it by 1000 (and floor it) just to get the current time in milliseconds since the epoch.
Instead, we can use `Process.clock_gettime` to get the current epoch time in milliseconds directly.

Performance: Use clock_gettime instead of converting Time object

---

instana.gemspec
lib/instana/agent.rb
test/agent/agent_test.rb

Switching to [Oj](https://github.com/ohler55/oj) gives us:
* faster json processing
* less memory
* less allocated objects
Some Ruby JSON related benchmarks are here:
https://github.com/stereobooster/ruby-json-benchmark

Switch to Oj for faster json processing.

---

lib/instana/instrumentation/grpc.rb
lib/instana/instrumentation/sidekiq-client.rb
lib/instana/instrumentation/sidekiq-worker.rb
test/instrumentation/redis_test.rb

Hi @pglombardo,
As you reported, the new redis client version has just changed its interface. This causes some problems:
- It breaks the test of Redis instrumentation (of course). I realize that we don't really need to stub the redis client. I removed all stub and  send invalid command to redis to simulate the cases that redis raises excpetion.
- The sidekiq instrumentation is affected too because we access the redis client via obsoleted interface. The host and port of redis client is now exposed with `connection` method, which is only available in new version. Therefore, I added a check `client.respond_to?(:connection)` to support both old and new interface.
In addition, gRPC gem has just changed the interface of gRPC server, which adds more params into handler method. Therefore, I added …

Fix gem interface backward compatibilities

---

lib/instana/agent.rb

Show code functionality was accidentally broken on the conversion to an alternate json processing strategy.
This PR fixes & improves host agent request processing (and Show Code functionality).

Fix host agent request processing

---

lib/instana/instrumentation/net-http.rb

In ruby's standard HTTP request library, the request method calls itself after starting the request. Therefore, in the instrumentation, the `log_exit` is called twic. Both calls close the current span and mess up the span tree.

Fix Net HTTP instrumentation closes wrong span

---

instana.gemspec

```
% bin/rails c
A, [2018-03-20T18:04:01.699610 #19726]   ANY -- : Stan is on the scene.  Starting Instana instrumentation.
W, [2018-03-20T18:04:01.851410 #19726]  WARN -- : Instana: Instrumenting GRPC client
W, [2018-03-20T18:04:01.852351 #19726]  WARN -- : Instana: Instrumenting GRPC server
W, [2018-03-20T18:04:01.853819 #19726]  WARN -- : Instana: Instrumenting Sidekiq client
/Users/rafaelsales/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'instana'.
Gem Load Error is: wrong number of arguments (given 1, expected 0)
Backtrace for gem load error is:
/Users/rafaelsales/.rbenv/versions/2.3.6/lib/ruby/gems/2.3.0/gems/sys-proctable-1.2.0/lib/darwin/sys/procta …
```

Fail to load rails console in development of MacOS

---

lib/instana/agent.rb
lib/instana/instrumentation/grpc.rb
lib/instana/instrumentation/sidekiq-client.rb
lib/instana/instrumentation/sidekiq-worker.rb

When I open rails console in my app, I get the following log entries in the STDOUT:
```
A, [2018-03-20T18:12:26.973106 #20062]   ANY -- : Stan is on the scene.  Starting Instana instrumentation.
W, [2018-03-20T18:12:27.104292 #20062]  WARN -- : Instana: Instrumenting GRPC client
W, [2018-03-20T18:12:27.105319 #20062]  WARN -- : Instana: Instrumenting GRPC server
W, [2018-03-20T18:12:27.106867 #20062]  WARN -- : Instana: Instrumenting Sidekiq client
```
I see a couple of issues here:
- These are not legit warnings, as there's nothing to fix. These should either be INFO or DEBUG.
- Customizing `::Instana.logger` on rails initializer didn't affect the log lines on app load
- Customizing `::Instana.logger.level = ::Logger::ERROR` on rails initializer didn't affect the log lines on app load #

Can't turn off warnings in console

---

instana.gemspec
lib/instana/util.rb

sys-proctable (used on OSX platforms only) changed the argument in `Proctable.ps` to a keyword argument which was a breaking change.
This PR updates the call and raised the dependency to be 1.2.0 or greater.

Update sys-proctable API call to follow upstream changes

---

lib/instana/agent.rb
lib/instana/frameworks/instrumentation/active_record.rb

* When unknown adapter, don't reference adapter name as it triggers a db connection
* Make sure binary exists before executing.

Add Safety and avoid triggering DB connections when unknown adapter

---

lib/instana/agent.rb

A minor improvement: it's a waste to report nulls over the wire.  Don't do that.

Span Reporting: Don't report nils

---

lib/instana/frameworks/rails.rb

* Honor the `::Instana.config[:tracing][:enabled]` config
* Inherit the Rails logger later in the boot process

Better Rails initialization

---

.travis.yml
lib/instana/instrumentation/rack.rb
lib/instana/instrumentation/resque.rb
lib/instana/instrumentation/sidekiq-worker.rb
test/frameworks/rack_test.rb

When the environment variable `INSTANA_SERVICE_NAME` is set, it names the process entity but it should also assure that this service name takes priority for reported traces.

Respect custom service name in in traces

---

lib/instana/instrumentation.rb

Currently if this key is set, all instrumentation is disabled, which is hard in some environments. This allows you to set this value to false to disable the disable.

Allow unsetting of INSTANA_DISABLE_AUTO_INSTR environment var

---

lib/instana/frameworks/instrumentation/action_controller.rb

We were noticing `NoMethodError`s being raised from [this line](https://github.com/instana/ruby-sensor/blob/1.9.5/lib/instana/frameworks/instrumentation/action_controller.rb#L20
). It looks like `has_rails_handler?` should have `exception` as an argument.
Also, this updates a call to `Instana.logger.debug` to build its log message within a block. This makes it so that we don't have to build the log message if our log level isn't `debug`.

Fix error in action controller has rails handler

---

lib/instana/frameworks/instrumentation/abstract_mysql_adapter.rb
lib/instana/frameworks/instrumentation/active_record.rb

A less common scenario of using two ActiveRecord adapters is not currently supported because of how we instrument ActiveRecord.  This PR allows multiple AR adapters to be instrumented simultaneously.

Rails: Support case of multiple ActiveRecord adapters

---

lib/instana/agent.rb
lib/instana/agent/helpers.rb
lib/instana/instrumentation/grpc.rb
lib/instana/instrumentation/resque.rb
lib/instana/tracing/span.rb
test/instrumentation/dalli_test.rb
test/instrumentation/excon_test.rb
test/instrumentation/rest-client_test.rb
test/instrumentation/sidekiq-client_test.rb
test/tracing/custom_test.rb
test/tracing/tracer_test.rb

When starting a new trace via OpenTracing or the bundled SDK, the first span in new traces now default to entry span kind.
https://docs.instana.io/quick_start/custom_tracing/#always-start-new-traces-with-entry-spans

Announce cleanup and better custom tracing defaults

---

instana.gemspec

The timers gem had a bug in versions >4.0.0 <4.0.4 causing a NoMethodError on the `now_and_every` method
https://github.com/socketry/timers/issues/50
This PR updates the gemspec to assure at least version 4.0.4 of the timers gem is installed.

Timers dependency: Assure min version of 4.0.4

---

lib/instana/agent.rb
lib/instana/agent/helpers.rb

At process boot, we usually wait for `:ready` state of the announce cycle to beging tracing.  This can take a few seconds and for command line execution, this can cause for some initial traces to be missed.
This PR changes this requirement to allow tracing after we've successfully announced to the Instana host agent but are pending `:ready` state so that traces are allowed to be collected much earlier in the boot process.

Tracing: Faster initial trace collection

---

lib/instana/instrumentation/rack.rb
test/frameworks/rails/actioncontroller_test.rb
test/servers/rails_3205.rb

This fixes a case where a Rack span may have been marked as errored because previous middleware in the stack may have passed a string status (not integer).
This seems to be valid according to the [Rack Spec](https://www.rubydoc.info/github/rack/rack/file/SPEC#label-The+Status).
We also add a bunch of 404 style tests to validate the case where this issue was originally seen.

Instana::Rack - Fix handling of a string status (convert to integer)

---

lib/instana/agent.rb

We usually have strict timeouts in the case of network issues or an overloaded host agent.
This PR allows for announce requests to have larger timeouts for new sensor initialization.

Agent: Make http timeouts configurable (internally)

---

lib/instana/agent/helpers.rb

Previously, we were incorrectly comparing if `'/' == "/\n"`

Container detection: chomp string before comparison

---

lib/instana/tracer.rb
test/tracing/opentracing_test.rb

This brings Instana::Tracer closer to the API defined by opentracing-ruby.

Support OpenTracing.start_active_span and OpenTracing.active_span

---

lib/instana/frameworks/cuba.rb
lib/instana/instrumentation/rack.rb
test/apps/cuba.rb
test/frameworks/cuba_test.rb
test/frameworks/rack_test.rb

These changes add [path template](https://www.instana.com/docs/tracing/custom-best-practices/#path-templates-visual-grouping-of-http-endpoints) support to Ruby applications written using the Cuba framework.

Cuba Path Template Support

---

lib/instana/frameworks/sinatra.rb
test/apps/sinatra.rb
test/frameworks/sinatra_test.rb

These changes add [path template](https://www.instana.com/docs/tracing/custom-best-practices/#path-templates-visual-grouping-of-http-endpoints) support to Ruby applications written using the Sinatra framework.

Path template support for Sinatra

---

lib/instana/frameworks/roda.rb
test/apps/roda.rb
test/frameworks/roda_test.rb

These changes add [path template](https://www.instana.com/docs/tracing/custom-best-practices/#path-templates-visual-grouping-of-http-endpoints) support to Ruby applications written using the Roda framework.

Path template support for Roda

---

lib/instana/frameworks/instrumentation/action_controller.rb
test/frameworks/rails/actioncontroller_test.rb

These changes add [path template](https://www.instana.com/docs/tracing/custom-best-practices/#path-templates-visual-grouping-of-http-endpoints) support to Ruby applications written using Rails.

Path template support for Rails

---

gemfiles/libraries.gemfile
lib/instana/config.rb
lib/instana/instrumentation/graphql.rb
lib/instana/tracing/span.rb
test/instrumentation/graphql_test.rb

These changes add support for [GraphQL Ruby](https://graphql-ruby.org/), generating all [expected and documented](https://www.instana.com/docs/ecosystem/graphql/) tags.

Support GraphQL Instrumentation

---

lib/instana/config.rb
lib/instana/frameworks/instrumentation/mysql2_adapter.rb
lib/instana/frameworks/instrumentation/mysql_adapter.rb
lib/instana/frameworks/instrumentation/postgresql_adapter.rb
test/frameworks/rails/activerecord_test.rb
test/test_helper.rb

By default, collected SQL will be sanitized to remove potentially sensitive bind params such as:
`> SELECT  "blocks".* FROM "blocks"  WHERE "blocks"."name" = "Mr. Smith"`
...would be sanitized to be:
`> SELECT  "blocks".* FROM "blocks"  WHERE "blocks"."name" = ?`
This sanitization step can be disabled by setting the following value to false in a initializer such as `config/initializers/instana.rb`:
```ruby
::Instana.config[:sanitize_sql] = false
```

Allow SQL sanitization to be disabled (default: on)

---

lib/instana/frameworks/instrumentation/abstract_mysql_adapter.rb
lib/instana/frameworks/instrumentation/action_view.rb
lib/instana/frameworks/instrumentation/active_record.rb
lib/instana/frameworks/instrumentation/mysql2_adapter.rb
lib/instana/frameworks/instrumentation/mysql_adapter.rb
lib/instana/frameworks/instrumentation/postgresql_adapter.rb
lib/instana/instrumentation/dalli.rb
lib/instana/instrumentation/grpc.rb
lib/instana/instrumentation/net-http.rb
lib/instana/instrumentation/redis.rb
lib/instana/instrumentation/resque.rb
lib/instana/instrumentation/rest-client.rb
lib/instana/util.rb
test/test_helper.rb

This remove the usage of method aliasing from our instrumentation. For context, see [this](https://www.justinweiss.com/articles/rails-5-module-number-prepend-and-the-end-of-alias-method-chain/).

Remove the usage of method aliasing in the instrumentation

---

lib/instana/activators/action_cable.rb
lib/instana/instrumentation/action_cable.rb
test/instrumentation/rails_action_cable_test.rb
test/instrumentation/rails_active_record_test.rb

This patch adds support for monitoring ActionCable. Each transmission sent to or action invoked on the cable will create a new RPC entry call linked to the web request that was hijacked to open the web socket.

Support ActionCable

---

lib/instana/activator.rb

If `INSTANA_ACTIVATE_SET` is present in the process environment, it will cause the library to only load the instrumentations listed. For example `env INSTANA_ACTIVATE_SET=rack,net_http bundle exec rails s` will only load the Rack and Net::HTTP instrumentations and skip all of the Rails ones. 
For all possible instrumentations see the list below:
<details>
<summary> Instrumentation List </summary>
```
action_cable
action_controller_api
action_controller_base
action_view
active_record
aws_sdk_dynamodb
aws_sdk_s3
aws_sdk_sns
aws_sdk_sqs
cuba
dalli
excon
graphql
grpc_client
grpc_server
net_http
rack
rails
redis
resque_client
resque_worker
rest_client
roda
shoryuken
sidekiq_client
sidekiq_worker
sinatra
```
</details>

Allow for INSTANA_ACTIVATE_SET to select the instrumentations to be loaded

---

lib/instana/activator.rb
lib/instana/config.rb
lib/instana/frameworks/rails.rb
lib/instana/instrumented_logger.rb
lib/instana/setup.rb
lib/instana/tracing/span.rb
test/tracing/instrumented_logger_test.rb

Includes a subclass of the standard logger which logs to Instana, and extends Rails' per-configured logger on versions 4 and above.

Support Instana's Log collection

---

lib/instana/activators/action_mailer.rb
lib/instana/instrumentation/action_mailer.rb
lib/instana/tracing/span.rb
test/instrumentation/rails_action_mailer_test.rb

Generate a new intermediate call when ActionMailer is invoked from within a tracing context.

Monitor ActionMailer

---

README.md

The repository has been renamed from
https://github.com/instana/nodejs-sensor
to
https://github.com/instana/nodejs.
[skip ci]

Update repository name for Node.js

---

lib/instana/config.rb
lib/instana/instrumentation/resque.rb
test/instrumentation/resque_test.rb
test/support/apps/resque/jobs/resque_fast_job.rb

In cases where the enqueue/dequeue behavior is being overridden setting `::Instana.config[:'resque-client'][:propagate] = false` allows a way to fall back to the "old" instrumentation and skip trace propagation.

Include a config option to disable Resque propagation

---

lib/instana/instrumentation/net-http.rb
lib/instana/secrets.rb
test/instrumentation/net_http_test.rb
test/secrets_test.rb

~Only capture uri.query if it's not nil~
Fix exception when remove_from_query is called with nil
fixes #250

Fix exception when remove_from_query is called with nil

---

.circleci/config.yml

`sonar.pullrequest.base` is missing because CircleCI doesn't expose the base branch in an environment variable.
https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
https://docs.sonarqube.org/9.0/analysis/pull-request/#header-4

Add SonarQube analysis parameter for PR analysis

---

lib/instana/tracing/span.rb
test/tracing/span_test.rb

Adds a config option called `backtrace_path_filter` that allows the lines in backtraces to be compared against the filter to see if they should be included in the backtrace
Backtraces are limited to a number of lines (default 30) and are often coming from so deep in library/framework code that you may not even see the originating user code in the backtrace. However, library code is often located in a different path than user code. This can be leveraged to filter the call stack to relevant code.
```ruby
[
'/usr/local/bundle/rails/...',
'/usr/local/bundle/rails/...',
'/usr/local/bundle/rails/...',
'/usr/local/bundle/rails/...',
'/usr/local/bundle/rails/...',
'/usr/local/bundle/rails/...',
'/usr/local/bundle/rails/...',
'/usr/local/bundle/rails/...',
'/usr/local/bundle/rails/...', …
```

Add backtrace_path_filter config option

---

lib/instana/instrumentation/shoryuken.rb

This is the last step of a multi-year header migration from using X_INSTANA_T/X_INSTANA_S with signed long values over using X_INSTANA_ST/X_INSTANA_SS with string values back to X_INSTANA_T/X_INSTANA_S with string values.
In this final step, we remove the fallback to the legacy header names X_INSTANA_ST/X_INSTANA_SS on the consumer side. Tracers have been sending X_INSTANA_T and X_INSTANA_S with string values since approximately January 2020, so the grace period for updating has been a generous 22 months.

chore(sqs, sns): remove fallback to legacy headers

---

lib/instana/backend/host_agent.rb
test/backend/host_agent_test.rb

Additional context:
* This is related to this sensor change: https://github.ibm.com/instana/sensors/pull/342 (released via https://github.ibm.com/instana/agent-update-site/pull/574 as discovery/sensor version 1.6.4). This has been rolled out in May already.
* The change in the agent-side sensor as well as in the in-process collector here are backwards compatible. I've tested that the old (< 1.6.4) discovery agent plug-in works with the updated in-process collector code and vice versa (new discovery plug-in 1.6.4 with old in-process collector code). Obviously I also tested the latest discovery version with the updated in-process collector code, that is, with this change.

Read extra http headers config from tracing object of discovery response

---

lib/instana/instrumentation/rack.rb
lib/instana/instrumentation/resque.rb
lib/instana/instrumentation/sidekiq-worker.rb
lib/instana/tracing/span.rb

Previously, we only added span.data.service to _entry_ spans (when the environment variable INSTANA_SERVICE_NAME is set). The requirements around this have changed, now we add this annotation to _all_ spans (but still only if it has been explicitly configured).
See also:
* https://github.ibm.com/instana/technical-documentation/pull/290/files
* https://instana.slack.com/archives/GBS2G15GD/p1675160462737709

feat: improve robustness of custom service naming

---

lib/instana/backend/host_agent_reporting_observer.rb
lib/instana/backend/process_info.rb
test/backend/process_info_test.rb

Problem:
The UI in `rubyRuntimePlatform/Dashboard/Content.js` uses the `formatter: kiloBytesTwoDecimalPlaces` for displaying the value in `plugins.rubyRuntimePlatform.dashboard.memory`.
Which essentially treats the unit of the value as a `Kilobyte`, This has not changed in a long long time.
In the ruby-sensor however in `c49f7dfe191f1cc3c0278042ddb76cbc5ff31181` things have changed,
the rss value propagation has been separated on the two mainly supported platforms `darwin` and  `linux` .
The orignal code previous to `c49f7dfe191f1cc3c0278042ddb76cbc5ff31181` was converting
the `rss` value to `kibibyte` on the top level, before sending the metrics.
After  `c49f7dfe191f1cc3c0278042ddb76cbc5ff31181`, for host agents (non-serverless),
the `rss` for `darwin` is read in `byte` and then …

fix: Change unit of memory to match the UI

---

lib/instana/backend/process_info.rb
lib/instana/version.rb

Prevents `NullPointerException` in the agent, because of announcing with `Announcement request: RubyProcess{pid='null', ...`.
Which happens on kernels where `/proc/[pid]/sched`is not available.

fix: Do not announce "nil" pid

---

lib/instana/config.rb
lib/instana/instrumentation/instrumented_request.rb
test/instrumentation/rack_instrumented_request_test.rb
test/instrumentation/rack_test.rb

The new test case in the tracer test suite is also failing for Ruby. (At first I thought it would not but that was only because the test suite accidentally ran an outdated set of test cases. This is fixed now.)
~~This PR should fix it. (Not tested locally with the test suite yet, though.)~~
Update 2023-05-22: This PR fixes that. I have tested this locally with the tracer test suite with the changes from this branch.

fix: handle newer format versions in traceparent with additional fields

---

lib/instana/instrumentation/graphql.rb
test/instrumentation/graphql_test.rb

Fixes: TS012739464 and at least partially TS012739440 as well

fix(graphql): Use class name if the object has no 'name' instance variable

---

.circleci/config.yml
gemfiles/dalli_30.gemfile
gemfiles/dalli_32.gemfile
lib/instana/activators/dalli.rb
lib/instana/instrumentation/dalli.rb

The `Dalli::Server` class has become deprecated.
From `3.0.0` up until `3.1.12` the same logic is in
`Dalli::Protocol::Binary`.
Starting with `3.1.12`, the request handling from
`Dalli::Protocol::Binary` has been moved to `Dalli::Protocol::Base`.
The `@hostname` and `@port` fields are dropped between in `v3.1.1`,
and only the `:hostname` and `:port` accessors  are available,
but those have been available even earlier, definitely
in the `2.0.0`, which is the oldest supported.

feat: Add support for latest Dalli versions

---

README.md

This small PR updates some dead `https://docs.instana.io` links in the README. I tried my best to map the old links to pages on [https://www.ibm.com/docs/en/instana-observability/current](https://www.ibm.com/docs/en/instana-observability/current?topic=ruby-configuration-configuring-instana-gem)

chore: update dead links in README

---

lib/instana/instrumentation/excon.rb
lib/instana/instrumentation/net-http.rb
lib/instana/instrumentation/rack.rb

Quote from the [spec](
https://github.ibm.com/instana/technical-documentation/tree/master/tracing/specification#capturing-errors-on-http-spans):
> For HTTP exit and entry spans alike, if a full request/response cycle has happened (which implies that an HTTP status code is present): If the HTTP status code is >= 500, the associated span MUST be marked as an error via span.ec.
This means that there is no upper limit, and this should apply to custom status codes as well, which might be above `511`, or even `599`.

fix: The spec doesn't set upper limit for ec=1 if code>=500

---

lib/instana/activators/sinatra.rb

And thus prevent crashes, when the instana thread calls sinatra/base.rb's compile function, which relies on this variable being initialized to an empty hash.
Backtarce was:
/usr/local/bundle/gems/sinatra-4.0.0/lib/sinatra/base.rb:1811:in `compile': undefined local variable or method `mustermann_opts' for Sinatra::Base:Class (NameError)
Mustermann.new(path, **mustermann_opts.merge(route_mustermann_opts))
^^^^^^^^^^^^^^^
from /usr/local/bundle/gems/sinatra-4.0.0/lib/sinatra/base.rb:1798:in `compile!'
from /usr/local/bundle/gems/sinatra-4.0.0/lib/sinatra/base.rb:1494:in `add_filter'
from /usr/local/bundle/gems/sinatra-4.0.0/lib/sinatra/base.rb:1489:in `after'
from /opt/instana/instrumentation/ruby/ruby/3.2.0/gems/instana-1.213.1/lib/instana/frameworks/sinatra.rb:16:in `store_path_template' …

fix(sinatra): Ensure that `mustermann_opts' is always defined

---

lib/instana/instrumentation/redis.rb

The breaking change that we have to adapt to is a change from `redis-client-0.22.0` to `redis-client-0.22.1`,
namely the signature of `pipelined` changed from
`def pipelined` to `pipelined(exception: true)`.
Now, that only Ruby 3 is supported, we can focus on explicitly delegating keyword arguments, which cover all future keyword and non-keyword argument changes.

fix: Wrong number of arguments redis_client.rb:424:in `pipelined'

---

lib/instana/backend/request_client.rb

Fixes the following exception, which happens,
when the require statement has raised an exception, but only after the 'Oj' name is already defined.
````
E, [2024-04-29T13:33:24.549280 #108] ERROR -- : undefined method `dump' for Oj:Module
defined?(Oj) ? Oj.dump(data, mode: :strict) : JSON.dump(data)
^^^^^
Did you mean?  dup
````

fix: Prevent usage of Oj once requiring it already raised an exception

---

.tekton/pipelinerun.yaml
.tekton/scheduled-eventlistener.yaml

The current `ruby-tracer-scheduled-ci-pipeline` takes ~55 minutes to complete. But sometimes it takes more than a hour which exceeds the default timeout of `1h`.

ci: Increase tekton PipelineRun timeout

---

lib/instana/activators/action_view.rb
lib/instana/instrumentation/action_view.rb
test/instrumentation/rails_action_view_test.rb
test/support/apps/action_view/config.ru
test/support/apps/action_view/views/test_view/render_collection.html.erb

… test app was not being initialised. So Instana activator for action view was not being triggered properly.

fix failing tests. The failures for rails v > 6.1

---

test/instrumentation/sidekiq-client_test.rb
test/instrumentation/sidekiq-worker_test.rb
test/secrets_test.rb
test/tracing/tracer_test.rb

Fixes the following error message
````
DEPRECATED: Use assert_nil if expecting nil
from /workspace/ruby-sensor/test/secrets_test.rb:97.
This will fail in Minitest 6.
````

test: Fix deprecation warning on incorrect assertion

---

instana.gemspec

Fixes the following 2 kinds of warnings:
````
lib/instana/backend/host_agent_lookup.rb:4: warning: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec.
lib/instana/serverless.rb:4: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec.
````

fix: Add missing gems for Ruby 3.3 and higher

---

test/tracing/span_test.rb

Fixes the following 2 warnings:
````
DEPRECATED: Use assert_nil if expecting nil from test/tracing/span_test.rb:12. This will fail in Minitest 6.
DEPRECATED: Use assert_nil if expecting nil from test/tracing/span_test.rb:13. This will fail in Minitest 6.
````

fix: Deprecated assertion on `nil` in `span_test`

---

.tekton/.currency/resources/table.json

We have been asked to update our markdown reports to change the Support Policy column.
For anything marked 30days, we are asked to revise to 45days.

report(currency): update tracer support policy 30->45

---

test/instrumentation/rails_active_record_test.rb

Deprecated name argument in remove_connection was causing issues. Initial method signature was **remove_connection(name = nil).** So removing the argument in this test file will fix the tests and should not have any repercussions on other areas.

fix: failing rails tests

---

lib/instana/instrumentation/active_record.rb
lib/instana/instrumentation/instrumented_request.rb
lib/instana/instrumentation/sequel.rb

From ruby 3.0 regular expression objects are immutable. So no need to freeze them.

fix: rubocop lint failures

---

lib/instana.rb

do not perform setup of the gem and remove the loaded instana module when INSTANA_DISABLE is set to true.
This solves #429

bug-429-do not perform setup of the gem

---

.circleci/config.yml
gemfiles/rails_80.gemfile

ci: start rails 8.0 testing

---

lib/instana.rb

unicorn worker was trying to delete the Instana constant twice. Hence adding check defined?

bug[429]: Unicorn remove the gem declaration if Instana disabled

---

lib/instana/instrumentation/active_job.rb

…d perform hook, this was causing problems with sidekiq dashboard

[Bug]: ActionMailer::MailDeliveryJob.arguments unexpected format for sidekiq

---

gemfiles/rails_61.gemfile
gemfiles/rails_70.gemfile
instana.gemspec

circleci: restrict concurrent-ruby to v-1.3.4 temporarily for rails 6 and 7. 
This issue is because of the recent release of concurrent-ruby(1.3.5). This issue should be fixed in later releases of rails or concurrent-ruby. Until then we will be using concurrent-ruby(1.3.5) for rails 6 and 7 testing.

restrict concurrent-ruby to v-1.3.4 temporarily

---

.tekton/.currency/scripts/generate_report.py

Updated currency generation script. New columns:
- Release date
- Latest Version Published At
- Days behind

currency: added new columns to currency report table

---

.circleci/config.yml

The publish workflow is failing because of the directory miss match. https://app.circleci.com/pipelines/github/instana/ruby-sensor/1906/workflows/9e5ee69a-374c-496b-aed8-d715134dfc97/jobs/278539

chore: fix gem publish job

---

.circleci/config.yml
Rakefile
lib/instana/setup.rb
lib/instana/span_filtering.rb
lib/instana/span_filtering/condition.rb
lib/instana/span_filtering/configuration.rb
lib/instana/span_filtering/filter_rule.rb
lib/instana/trace/span.rb
test/instrumentation/redis_test.rb
test/span_filtering/condition_test.rb
test/span_filtering/configuration_test.rb
test/span_filtering/filter_rule_test.rb
test/span_filtering/span_filtering_test.rb

Adds span filtering capabilities based on the tracer configuration

Redis span filtering
